import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Ctrl + Space to see the available fonts
import "./globals.css";
import NavBar from "@/components/NavBar";
import { NotesContextProvider } from "@/context/NoteContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  openGraph: {
    title: "Next App",
    description: "Generated by create next app",
    siteName: "Next App",
    // url: "https://nextjs.org",
    images: [
      {
        url: "https://og-image.vercel.app/**Next.js**%20**App**.png",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en-US",
    type: "website",
  },
  title: "Next.js App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  applicationName: "Next.js App",
  robots: {
    index: true,
    follow: true,
  },
  verification: {
    google: "google-site-verification-code",
  },
  authors: [{ name: "KarlDev95", url: ''}],
  creator: "KarlDev95",
  keywords: "Next.js, TypeScript, Tailwind CSS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotesContextProvider>
          <NavBar />
          {children}
        </NotesContextProvider>
      </body>
    </html>
  );
}
